# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $UsernameEncoded = [System.Web.HttpUtility]::UrlEncode($(gitUsername))
      $PasswordEncoded = [System.Web.HttpUtility]::UrlEncode($(gitPassword))
      $newRemoteUrlBuilder = New-Object System.UriBuilder($currentRemoteUri)
      $newRemoteUrlBuilder.UserName = $UsernameEncoded 
      $newRemoteUrlBuilder.Password = $PasswordEncoded
      $gitAuthenticatedUrl = $newRemoteUrlBuilder.ToString()
      git clone $gitAuthenticatedUrl
