name: Examine Build

on:
  push:
    branches:    
      - 'release/2.0.0'
  pull_request:
    branches:
      - 'release/2.0.0'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    env:
      Solution_File: src/Examine.sln
      Test_Folder: src/Examine.Test
      Configuration: Release
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create copyright value
      run: |
        $Copyright = "Copyright " + [char]0x00A9 + " Shannon Deminick " + (Get-Date).year
        echo ("Copyright=" + $Copyright) >> $Env:GITHUB_ENV
      shell: pwsh
      
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.9
    
    - name: Install dependencies
      run: dotnet restore $env:Solution_File
    
    - name: Build
      run: dotnet build $env:Solution_File --configuration $env:Configuration --no-restore
    
    - name: Test
      run: dotnet test "${{ env.Test_Folder }}/bin/${{ env.Configuration }}/Examine.Test.dll" --no-build --verbosity normal --results-directory ${{ github.workspace }}/_TestResults  --logger "trx;logfilename=tests.trx"
    

    - uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path:  ${{ github.workspace }}/_TestResults/tests.trx
